// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1YKfU4ntpX_AiyeGLtK4KU6PSFCotkBI',
    appId: '1:250721309748:web:0dce3ffbee41197a2de661',
    messagingSenderId: '250721309748',
    projectId: 'elio-apps',
    authDomain: 'elio-apps.firebaseapp.com',
    storageBucket: 'elio-apps.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5iA47llSLHLXUO18-jOelSFp1Z9rpdbI',
    appId: '1:250721309748:android:025a3ad6bd616e882de661',
    messagingSenderId: '250721309748',
    projectId: 'elio-apps',
    storageBucket: 'elio-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPH_l8hvknnCA6fE6PppKzGZT2gUhsliY',
    appId: '1:250721309748:ios:842da756aed9cc652de661',
    messagingSenderId: '250721309748',
    projectId: 'elio-apps',
    storageBucket: 'elio-apps.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPH_l8hvknnCA6fE6PppKzGZT2gUhsliY',
    appId: '1:250721309748:ios:842da756aed9cc652de661',
    messagingSenderId: '250721309748',
    projectId: 'elio-apps',
    storageBucket: 'elio-apps.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1YKfU4ntpX_AiyeGLtK4KU6PSFCotkBI',
    appId: '1:250721309748:web:f540a17e05b7cb6c2de661',
    messagingSenderId: '250721309748',
    projectId: 'elio-apps',
    authDomain: 'elio-apps.firebaseapp.com',
    storageBucket: 'elio-apps.firebasestorage.app',
  );
}
